### ISSUE TITLE
Complete Phase 1 Activities

### ISSUE THREAD

**Issue by elifleaf** [ertekin-research-group/papercool#1]
# Summary
Track progress on Phase 1 activities here.   Submit Phase 1 materials for review when completed

# Phase 1 Activities. 
Note: detailed instructions and guidelines for each activity are available. Make sure that you follow them.
- [ ] Write one concise, coherent sentence that summarizes the main theme of your paper; build a list of your supporting evidence for your theme. 
- [ ] Write the abstract 
- [ ] Prepare figures and captions 
- [ ] Present all of the above to your review team. 
- [ ] Submit materials to Elif. 

## Useful advice. 
A technical paper is not like a movie.  As such, the logic flow and development do not follow the typical arc of a cinematic story.  In a movie, usually the plot slowly builds, reaches a climax where  something big and new is revealed, and then the remaining pieces to be sorted out get sorted out at the end.

In a technical paper, there is no moment of big reveal.  Don't build your story like its some sort of mystery. State directly up front and at the beginning what you discovered.  Then use the rest of the paper to provide your supporting evidence.  Think more like you are a lawyer: you first state your argument, and then you systematically and logically build a case for your argument by showing supporting evidences.  

Spare your audience the details of your personal experience of how you learned what you learned.  It's not about you; its about the science.  Avoid chronologically presenting information in the  order in which you obtained it; present your argument in the form that builds the strongest fact-based case possible.
