### ISSUE TITLE
Complete Phase 3 Activities

### ISSUE THREAD

**Issue by elifleaf** [ertekin-research-group/papercool#6]
# Summary
Track progress on Phase 3 activities here.   Submit Phase 3 materials for review when completed

# Phase 1 Activities. 
Note: detailed instructions and guidelines for each activity are available. Make sure that you follow them.
- [ ] Turn outline of introduction into smooth, concise written text. 
- [ ] Turn outline of methods section into smooth, concise written text.  
- [ ] Turn outline of results and discussion section(s) into smooth, concise written text. 
- [ ] Turn outline of conclusion into smooth, concise written text.
